version: "3.9"

services:
  healthcare-ai-assistant:
    build: .
    container_name: healthcare-ai-assistant

    ports:
      - "8000:8000"

    volumes:
      - ./data:/app/data
      - ./vector_store:/app/vector_store

    env_file:
      - .env

    restart: unless-stopped